config/routes.rb
Rails.application.routes.draw do
  resources :harvesting_records

  resources :plantings

  resources :active_plants
  

  resources :active_plant_records

  resources :harvest_types

  resources :daily_records

  resources :soils

  resources :moon_phases

  resources :plant_statuses

  resources :plants

   post 'locations/edit_multiple', :to => 'locations#edit_multiple', :as => 'locations_edit_multiple' 

  put 'locations/update_multiple', :to =>  'locations#update_multiple', :as => 'locations_update_multiple' 
   
  resources :locations
  
   

  resources :water_amounts

  root 'base#index'

end

app/models/active_plant.rb
class ActivePlant < ActiveRecord::Base
   belongs_to :plant, class_name: "Plant"
   belongs_to :plant_status, class_name: "PlantStatus"
   belongs_to :location, class_name: "Location"
   belongs_to :soil, class_name: "Soil"
   has_many :harvest_records
   has_one :planting
   
   
   attr_accessor :date_planted, :nutrients_added, :watered

   validates :plant_id, :location_id, :plant_status_id, :count_active, presence: true

end

app/models/active_plant_record.rb
class ActivePlantRecord < ActiveRecord::Base
   belongs_to :active_plant
   belongs_to :plant_status   
end

app/models/daily_record.rb
class DailyRecord < ActiveRecord::Base
   #enum precipitation: { "None" => 0, "Dew" => 1, "Sprinkled" => 2, "Light Shower" => 3, "Quick Rain" => 4, "Rain" => 5, "Long Rain" => 6, "Heavy Rain" => 7, "Serious Rain" => 8, "Almost Flood" => 9, "Cats and Dogs" => 10 }
   belongs_to :moon_phase
   
   validates :daily_date, :weather, presence: true
   validates :temp_high, :temp_low, :eggs_collected, :total_ducks, :moon_percent, :precipitation, numericality: true
   
   validates :daily_date, uniqueness: true
end

app/models/harvest_type.rb
class HarvestType < ActiveRecord::Base
end

app/models/harvesting_record.rb
class HarvestingRecord < ActiveRecord::Base
   belongs_to :active_plant, class_name: "ActivePlant"
   belongs_to :weight_type, class_name: "WeightType"
   
   validates :active_plant_id, :date_harvested, :count_harvested, :weight_type_id, presence: true

end

app/models/location.rb
class Location < ActiveRecord::Base
   validates :name, :soil_id, presence: true
   belongs_to :soil, class_name: "Soil"
   
end

app/models/moon_phase.rb
class MoonPhase < ActiveRecord::Base
end

app/models/plant.rb
class Plant < ActiveRecord::Base   
   belongs_to :harvest_type
   belongs_to :water_amount
   belongs_to :plant_status
   validates :name, uniqueness: true
   validates :name, :plant_type, :plant_group,  presence: true #:harvest_type_id, :water_amount_id,
   #
end

app/models/plant_status.rb
class PlantStatus < ActiveRecord::Base
end

app/models/planting.rb
class Planting < ActiveRecord::Base
   belongs_to :active_plant
   belongs_to :plant_status
   belongs_to :location
   belongs_to :soil
   
end

app/models/soil.rb
class Soil < ActiveRecord::Base
      validates :name, presence: true

end

app/models/water_amount.rb
class WaterAmount < ActiveRecord::Base
  validates :name, presence: true
end

app/models/weight_type.rb
class WeightType < ActiveRecord::Base
  validates :name, presence: true
end

app/controllers/active_plants_controller.rb
class ActivePlantsController < ApplicationController
   before_action :set_active_plant, only: [:show, :edit, :update, :destroy]
   require 'date'
   
  # GET /active_plants
  # GET /active_plants.json
  def index
     if(!params[:sort].nil?)
        @active_plants = ActivePlant.joins(:plant).where("plant_status_id < ?", 8).order(params[:sort] + ' ' + params[:direction])
     else
        @active_plants = ActivePlant.where("plant_status_id < ?", 8).order(:location_id, :plant_id).all
     end
  end

  # GET /active_plants/1
  # GET /active_plants/1.json
  def show
     #Inner Join
     #@active_plant = ActivePlant.joins(:planting)
     @planting = Planting.where(active_plant_id: @active_plant.id).first
     
     puts @planting.inspect
     @harvesting_records = HarvestingRecord.where(active_plant_id: @active_plant.id).order(:date_harvested)

     #@active_plant = ActivePlant.find(params[:id])

  end

  # GET /active_plants/new
  def new
   @active_plant = ActivePlant.new
  end

  # GET /active_plants/1/edit
  def edit
  end
   
     # GET /active_plants/1/edit
  def admin_edit
  end

  # POST /active_plants
  # POST /active_plants.json
   def create
      #TODO date
      puts "active_plant_params="+params.inspect
      @start_date = Date.civil(params[:range][:"start_date(1i)"].to_i,params[:range][:"start_date(2i)"].to_i,params[:range][:"start_date(3i)"].to_i)
      @active_plant = ActivePlant.new(active_plant_params)
      respond_to do |format|
      if @active_plant.save
         #Create a Planting record
         @planting = Planting.create(active_plant_id: @active_plant.id, plant_status_id: active_plant_params[:plant_status_id], location_id: @active_plant.location_id, count_planted: active_plant_params[:count_active], date_planted: @start_date, comment: @active_plant.comment)
         
         @planting.save
         format.html { redirect_to @active_plant, notice: 'Active plant was successfully created.  Planting Data saved.' }
         format.json { render :show, plant_status_id: :created, location: @active_plant }
      else
        format.html { render :new }
        format.json { render json: @active_plant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /active_plants/1
  # PATCH/PUT /active_plants/1.json
  def update
     action_date = Date.civil(params[:range][:"start_date(1i)"].to_i,params[:range][:"start_date(2i)"].to_i,params[:range][:"start_date(3i)"].to_i)
       if(params[:active_plant][:nutrients_added] == "1")
          puts "$$$$.$$ got nutrients :)"
          params[:active_plant][:last_nutrient_date] = action_date
       end          
     puts "$$$$.$$ Update active_plant_params="+params.inspect

     respond_to do |format|             
     if @active_plant.update(active_plant_params)
        @planting = ActivePlantRecord.create(active_plant_id: @active_plant.id, plant_status_id: active_plant_params[:plant_status_id], count_active: active_plant_params[:count_active], date_processed: action_date, nutrients_added: params[:active_plant][:nutrients_added], comment: @active_plant.comment)

        #TODO update harvest data if needed.
        format.html { redirect_to @active_plant, notice: 'Active plant was successfully updated.' }
        format.json { render :show, status: :ok, location: @active_plant }
      else
        format.html { render :edit }
        format.json { render json: @active_plant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /active_plants/1
  # DELETE /active_plants/1.json
  def destroy
    @active_plant.destroy
    respond_to do |format|
      format.html { redirect_to active_plants_url, notice: 'Active plant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def sort_column  
       ActivePlant.column_names.include?(params[:sort]) ? params[:sort] : "location_id"    
    end
   
    def set_active_plant
      @active_plant = ActivePlant.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def active_plant_params
       params.require(:active_plant).permit(:plant_id, :plant_status_id, :location_id, :soil_id, :count_active, :nutrients_added, :comment)
    end
end

app/helpers/active_plants_helper.rb
module ActivePlantsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def sortable(title = nil, column)  
    title ||= column.titleize  
    css_class = (column == sort_column) ? "current #{sort_direction}" : nil  
    font_icon = (column == sort_column) ? "<i class=\"fi-up-arrow small\"></i>" : nil  
    direction = (column == sort_column && sort_direction == "asc") ? "desc" : "asc"  
     link_to raw("#{font_icon} #{title}"), {:sort => column, :direction => direction}, {:class => css_class}  
  end  
end

app/helpers/base_helper.rb
module BaseHelper
end

app/helpers/daily_data_helper.rb
module DailyDataHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/moon_phases_helper.rb
module MoonPhasesHelper
end

app/helpers/plantings_helper.rb
module PlantingsHelper
end

app/helpers/plants_helper.rb
module PlantsHelper
end

app/helpers/soils_helper.rb
module SoilsHelper
end

app/views/active_plants/_form.html.erb
<div class="row">
  <div class="small-12 columns">
    <%= simple_form_for(@active_plant) do |f| %>
      <% if @active_plant.errors.any? %>
        <div class="div.alert-box.alert.round" id="error_explanation">
          <h2><%= pluralize(@active_plant.errors.count, "error") %> prohibited this active plant from being saved:</h2>
          <ul>
      <% @active_plant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
        </div>
      <% end %>
      <%= f.input :plant_id, collection: Plant.order('name ASC').all, label_method: lambda { |ap| "#{ap.plant_type}: #{ap.name}" },  prompt: "Choose wisely" %>
      <td> Location </td>
      <%= f.collection_select :location_id, Location.all, :id, :name,   prompt: "Choose wisely", label: "Location" %>
      <%= f.input :plant_status_id, collection: PlantStatus.all, prompt: "Choose wisely" %>
      <%= f.input :count_active %><br>
      <td> Date Planted </td>
      <%= date_select('range', 'start_date', :order => [:month, :day, :year])%>

      <%= f.input :comment %><br>
      <%= f.button :submit %>
    <% end %>
  </div>
</div>

app/views/active_plants/_form_update.erb
<div class="row">
   This is an Update form 
   <div class="small-12 columns">
      <%= simple_form_for(@active_plant) do |f| %>
      <% if @active_plant.errors.any? %>
         <div class="div.alert-box.alert.round" id="error_explanation">
            <h2><%= pluralize(@active_plant.errors.count, "error") %> prohibited this active plant from being saved:</h2>
            <ul>
               <% @active_plant.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
               <% end %>
            </ul>
         </div>
      <% end %>
      <div class="small-12 columns">
         <div class="small-6 columns">
            <h5><%= @active_plant.plant.name %> in <%= @active_plant.location.name %></h5>
         </div>
         <div class="small-6 columns">
            <h5>Current status: <%= @active_plant.plant_status.name %></h5>
         </div>
         <%= f.input :plant_id, collection: Plant.order('name ASC').all, prompt: "Choose wisely" %>
      </div>
      <div class="small-12 columns">
         <%= f.input :location_id, collection: Location.all, label: "Change Location..." %>
      </div>
      <div class="small-12 columns">
         <%= f.input :plant_status_id, collection: PlantStatus.all, label: "Change Status..." %>
      </div>
      <div class="small-12 columns">
         <%= f.input :count_active %><br>
      </div>
      <div class="small-6 columns">
        <div class="small-12 columns">
           <%= f.input :nutrients_added, as: :boolean %><br>
        </div>
     </div>
     <div class="small-6 columns">
        Date of action:
        <%= date_select('range', 'start_date', :order => [:month, :day, :year])%>
     </div>
     <%= f.input :comment %><br>
     <%= f.button :submit %>
    <% end %>
  </div>
</div>

app/views/active_plants/edit.html.erb
<h4 align="center">Updating Active Plant</h4>

<%= render 'form_update' %>   
<div class="row">
   <div class="small-4 columns">
      <%= link_to 'All Active Plants', active_plants_path %>
   </div>
   <div class="small-4 columns">
      <p class="text-center"><%= link_to 'Show', @active_plant %> </p>
   </div>
   <div class="small-4 columns">
      <p class="text-right"><%= link_to 'New Active Plant', new_active_plant_path, { :class=>"button small round success" } %></p>
   </div>
</div>

app/views/active_plants/index.html.erb
<div class="row">
  <div class="small-12 columns">
      <h1>Listing Active Plants</h1>
      <p class="text-left"><%= link_to 'New Active Plant', new_active_plant_path, { :class=>"button small round success" }  %></p>
      <table>
        <thead>
          <tr>
             <th><%= sortable "Plant", "plants.name" %></th>
             <th><%= sortable "Status", "plant_status_id" %></th>
             <th><%= sortable "Location", "location_id" %></th>
             <th><%= sortable "Active", "count_active" %></th>
             <th><%= sortable "Comment", "comment" %></th>
            <th colspan="2"></th>
          </tr>
        </thead>
        <tbody>
          <% @active_plants.each do |active_plant| %>
            <tr>
               <% if active_plant.plant_id? %>
               <td>
                  <%= link_to raw('<i class="fi-eye"></i>'), active_plant %> | 
                  <%= link_to "#{active_plant.plant.name} #{active_plant.plant.plant_type}", plant_path(active_plant.plant)%>
               </td>
               <td>
                  <%= link_to raw('<i class="fi-calendar"></i>'), planting_path(active_plant) %> | 
                  <%= active_plant.plant_status.name if active_plant.plant_status_id %>
               </td>
               <td><%= link_to active_plant.location.name, location_path(active_plant.location) %></td>
               <td><%= active_plant.count_active %></td>
               <td><%= active_plant.comment %></td>
               <% end %>
               <td>
                  <%= link_to raw('<i class="fi-pencil"></i>'), edit_active_plant_path(active_plant) %> | 
                  <%= link_to raw('<i class="fi-plus"></i>'), new_harvesting_record_path(active_plant), :active_plant_id => active_plant.id %> | 
                  <%= link_to raw('<i class="fi-trash"></i>'), active_plant, method: :delete, data: { confirm: 'Are you sure?' } %>
               </td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <br>
      <p class="text-left"><%= link_to 'New Active Plant', new_active_plant_path, { :class=>"button small round success" }  %></p>
      <div class="row">
         <div class="small-4 columns">
            <%= link_to 'Plantings', plantings_path, { :class=>"button small round disabled" }  %>
         </div>
         <div class="small-4 columns">
            <p class="text-center"><%= link_to 'Harvests', harvesting_records_path, { :class=>"button small round disabled" }  %> </p>
         </div>
         <div class="small-4 columns">
            <p class="text-right"><%= link_to 'Records', active_plant_records_path, { :class=>"button small round disabled" }  %></p>
         </div>
      </div>
     
   </div>
</div>

app/views/active_plants/new.html.erb
<h1>New Active Plant</h1>
<h2>Creates planting data.</h2>

<%= render 'form' %>


<div class="row">
   <div class="small-4 columns">
      <%= link_to 'All Active Plants', active_plants_path %>
   </div>
   <div class="small-4 columns">
   </div>
   <div class="small-4 columns">
   </div>
</div>

app/views/active_plants/show.html.erb
<div class="row">
   <div class="small-6 columns">
      <h3>Active Plant</h3>
      <p id="notice"><%= notice %></p>
      <table>
         <tr>
            <td><strong>Plant:</strong></td>
            <td><%= @active_plant.plant.name %></td>
         </tr>
         <tr>
            <td><strong>Status:</strong></td>
            <td><%= @active_plant.plant_status.name if @active_plant.plant_status_id%></td>
         </tr>
         <tr>
            <td><strong>Location:</strong></td>
            <td><%= @active_plant.location.name %></td>
         </tr>
         <tr>
            <td><strong>Count active:</strong></td>
            <td><%= @active_plant.count_active %></td>
         </tr>
         <tr>
            <td><strong>Comment:</strong></td>
            <td><%= @active_plant.comment %></td>
         </tr>
         <tr>
            <td><strong>Planted:</strong></td>
            <td><%= link_to @planting.date_planted, planting_path(@planting) %></td>
         </tr>
      </table>
   </div>
   <div class="small-6 columns">
      <%= render partial: '/harvesting_records/past_harvests', :locals => {:align_direction => 'right', :show_all_harvests => true}  %>
   </div>
</div>
   
<div class="row">
   <div class="small-4 columns">
      <%= link_to 'All Active Plants', active_plants_path %>
   </div>
   <div class="small-4 columns">
      <p class="text-center"><%= link_to 'Edit', edit_active_plant_path(@active_plant) %> </p>
   </div>
   <div class="small-4 columns">
      <p class="text-right"><%= link_to 'Harvest', new_harvesting_record_path(@active_plant), { :class=>"button small round alert", :active_plant_id => @active_plant.id} %></p>
   </div>
</div>