config/routes.rb
Rails.application.routes.draw do
  resources :harvesting_records

  resources :plantings

  resources :active_plants
  

  resources :active_plant_records

  resources :harvest_types

  resources :daily_records

  resources :soils

  resources :moon_phases

  resources :plant_statuses

  resources :plants

   post 'locations/edit_multiple', :to => 'locations#edit_multiple', :as => 'locations_edit_multiple' 

  put 'locations/update_multiple', :to =>  'locations#update_multiple', :as => 'locations_update_multiple' 
   
  resources :locations
  
   

  resources :water_amounts

  root 'base#index'

end

app/models/active_plant.rb
class ActivePlant < ActiveRecord::Base
   belongs_to :plant, class_name: "Plant"
   belongs_to :plant_status, class_name: "PlantStatus"
   belongs_to :location, class_name: "Location"
   belongs_to :soil, class_name: "Soil"
   has_many :harvest_records
   has_one :planting
   
   
   attr_accessor :date_planted, :nutrients_added, :watered

   validates :plant_id, :location_id, :plant_status_id, :count_active, presence: true

end

app/models/active_plant_record.rb
class ActivePlantRecord < ActiveRecord::Base
   belongs_to :active_plant
   belongs_to :plant_status   
end

app/models/daily_record.rb
class DailyRecord < ActiveRecord::Base
   #enum precipitation: { "None" => 0, "Dew" => 1, "Sprinkled" => 2, "Light Shower" => 3, "Quick Rain" => 4, "Rain" => 5, "Long Rain" => 6, "Heavy Rain" => 7, "Serious Rain" => 8, "Almost Flood" => 9, "Cats and Dogs" => 10 }
   belongs_to :moon_phase
   
   validates :daily_date, :weather, presence: true
   validates :temp_high, :temp_low, :eggs_collected, :total_ducks, :moon_percent, :precipitation, numericality: true
   
   validates :daily_date, uniqueness: true
end

app/models/harvest_type.rb
class HarvestType < ActiveRecord::Base
end

app/models/harvesting_record.rb
class HarvestingRecord < ActiveRecord::Base
   belongs_to :active_plant, class_name: "ActivePlant"
   belongs_to :weight_type, class_name: "WeightType"
   
   validates :active_plant_id, :date_harvested, :count_harvested, :weight_type_id, presence: true

end

app/models/location.rb
class Location < ActiveRecord::Base
   validates :name, :soil_id, presence: true
   belongs_to :soil, class_name: "Soil"
   
end

app/models/moon_phase.rb
class MoonPhase < ActiveRecord::Base
end

app/models/plant.rb
class Plant < ActiveRecord::Base   
   belongs_to :harvest_type
   belongs_to :water_amount
   belongs_to :plant_status
   validates :name, uniqueness: true
   validates :name, :plant_type, :plant_group,  presence: true #:harvest_type_id, :water_amount_id,
   #
end

app/models/plant_status.rb
class PlantStatus < ActiveRecord::Base
end

app/models/planting.rb
class Planting < ActiveRecord::Base
   belongs_to :active_plant
   belongs_to :plant_status
   belongs_to :location
   belongs_to :soil
   
end

app/models/soil.rb
class Soil < ActiveRecord::Base
      validates :name, presence: true

end

app/models/water_amount.rb
class WaterAmount < ActiveRecord::Base
  validates :name, presence: true
end

app/models/weight_type.rb
class WeightType < ActiveRecord::Base
  validates :name, presence: true
end

app/controllers/base_controller.rb
class BaseController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
  def sortable(title = nil, column)  
    title ||= column.titleize  
    css_class = (column == sort_column) ? "current #{sort_direction}" : nil  
    font_icon = (column == sort_column) ? "<i class=\"fi-up-arrow small\"></i>" : nil  
    direction = (column == sort_column && sort_direction == "asc") ? "desc" : "asc"  
     link_to raw("#{font_icon} #{title}"), {:sort => column, :direction => direction}, {:class => css_class}  
  end  
end

app/helpers/base_helper.rb
module BaseHelper
end

app/helpers/daily_data_helper.rb
module DailyDataHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/moon_phases_helper.rb
module MoonPhasesHelper
end

app/helpers/plantings_helper.rb
module PlantingsHelper
end

app/helpers/plants_helper.rb
module PlantsHelper
end

app/helpers/soils_helper.rb
module SoilsHelper
end

app/views/base/_footer.html.erb
<hr>
<div align="center"> 
   <%= link_to "Home", root_path, { :class=>"button small round success" } %>
</div>
   <div>
</div>

app/views/base/_header.html.erb
<head>
<% javascript_include_tag "vendor/modernizr" %>
<meta name="viewport" content="width=device-width, initial-scale=1.0" />

</head>
<div class="row">
   <div class="columns mall-12">
   <%=  link_to((image_tag("oof.jpg", data: { src: "oof.oof", src_retina: "oof.oof" } )) , '/')
%>
      

app/views/base/index.html.erb
<h2 align="center">Home</h2>
<table align="center">
  <tr> 
     <th class="text-center"><%= link_to "Plants",  plants_path, { :class=>"button tiny disabled" } %></th>
     <th class="text-center"><%= link_to "Soils",  soils_path, { :class=>"button tiny disabled" }  %></th>
     <th class="text-center"><%= link_to "Locations",  locations_path, { :class=>"button tiny disabled" }  %></th>
  </tr> 
  <tr> 
     <th class="text-center"><%= link_to "Plantings",  plantings_path, { :class=>"button small round success" }  %></th>
     <th class="text-center"><%= link_to "Active Plants",  active_plants_path, { :class=>"red button medium round nice" }  %></th>
     <th class="text-center"><%= link_to "Records",  active_plant_records_path, { :class=>"button small round disabled" }  %></th>
  </tr> 
  <tr>
     <th class="text-center"><%= link_to "Harvesting",  harvesting_records_path, { :class=>"button small round alert" }  %></th>
     <th class="text-center"></th>
     <th class="text-center"><%= link_to "Daily Records",  daily_records_path, { :class=>"button small round disabled" }  %></th>
  </tr>  
</table>