config/routes.rb
Rails.application.routes.draw do
  resources :harvesting_records

  resources :plantings

  resources :active_plants
  

  resources :active_plant_records

  resources :harvest_types

  resources :daily_records

  resources :soils

  resources :moon_phases

  resources :plant_statuses

  resources :plants

   post 'locations/edit_multiple', :to => 'locations#edit_multiple', :as => 'locations_edit_multiple' 

  put 'locations/update_multiple', :to =>  'locations#update_multiple', :as => 'locations_update_multiple' 
   
  resources :locations
  
   

  resources :water_amounts

  root 'base#index'

end

app/models/active_plant.rb
class ActivePlant < ActiveRecord::Base
   belongs_to :plant, class_name: "Plant"
   belongs_to :plant_status, class_name: "PlantStatus"
   belongs_to :location, class_name: "Location"
   belongs_to :soil, class_name: "Soil"
   has_many :harvest_records
   has_one :planting
   
   
   attr_accessor :date_planted, :nutrients_added, :watered

   validates :plant_id, :location_id, :plant_status_id, :count_active, presence: true

end

app/models/active_plant_record.rb
class ActivePlantRecord < ActiveRecord::Base
   belongs_to :active_plant
   belongs_to :plant_status   
end

app/models/daily_record.rb
class DailyRecord < ActiveRecord::Base
   #enum precipitation: { "None" => 0, "Dew" => 1, "Sprinkled" => 2, "Light Shower" => 3, "Quick Rain" => 4, "Rain" => 5, "Long Rain" => 6, "Heavy Rain" => 7, "Serious Rain" => 8, "Almost Flood" => 9, "Cats and Dogs" => 10 }
   belongs_to :moon_phase
   
   validates :daily_date, :weather, presence: true
   validates :temp_high, :temp_low, :eggs_collected, :total_ducks, :moon_percent, :precipitation, numericality: true
   
   validates :daily_date, uniqueness: true
end

app/models/harvest_type.rb
class HarvestType < ActiveRecord::Base
end

app/models/harvesting_record.rb
class HarvestingRecord < ActiveRecord::Base
   belongs_to :active_plant, class_name: "ActivePlant"
   belongs_to :weight_type, class_name: "WeightType"
   
   validates :active_plant_id, :date_harvested, :count_harvested, :weight_type_id, presence: true

end

app/models/location.rb
class Location < ActiveRecord::Base
   validates :name, :soil_id, presence: true
   belongs_to :soil, class_name: "Soil"
   
end

app/models/moon_phase.rb
class MoonPhase < ActiveRecord::Base
end

app/models/plant.rb
class Plant < ActiveRecord::Base   
   belongs_to :harvest_type
   belongs_to :water_amount
   belongs_to :plant_status
   validates :name, uniqueness: true
   validates :name, :plant_type, :plant_group,  presence: true #:harvest_type_id, :water_amount_id,
   #
end

app/models/plant_status.rb
class PlantStatus < ActiveRecord::Base
end

app/models/planting.rb
class Planting < ActiveRecord::Base
   belongs_to :active_plant
   belongs_to :plant_status
   belongs_to :location
   belongs_to :soil
   
end

app/models/soil.rb
class Soil < ActiveRecord::Base
      validates :name, presence: true

end

app/models/water_amount.rb
class WaterAmount < ActiveRecord::Base
  validates :name, presence: true
end

app/models/weight_type.rb
class WeightType < ActiveRecord::Base
  validates :name, presence: true
end

app/controllers/base_controller.rb
class BaseController < ApplicationController
end

app/controllers/plants_controller.rb
class PlantsController < ApplicationController
  helper_method :sort_column, :sort_direction
  before_action :set_plant, only: [:show, :edit, :update, :destroy]

  # GET /plants
  # GET /plants.json
  def index
     if(!params[:sort].nil?)
        @plants = Plant.order(params[:sort] + ' ' + params[:direction]).all
     else
        @plants = Plant.order(:name).all
     end
  end

  # GET /plants/1
  # GET /plants/1.json
  def show
  end

  # GET /plants/new
  def new
    @plant = Plant.new
  end

  # GET /plants/1/edit
  def edit
  end

  # POST /plants
  # POST /plants.json
  def create
    @plant = Plant.new(plant_params)
   puts "plant_params"+plant_params.to_s
    respond_to do |format|
      if @plant.save
        format.html { redirect_to @plant, notice: 'Plant was successfully created.' }
        format.json { render :show, status: :created, location: @plant }
      else
        format.html { render :new }
        format.json { render json: @plant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /plants/1
  # PATCH/PUT /plants/1.json
  def update
    respond_to do |format|
      if @plant.update(plant_params)
        format.html { redirect_to @plant, notice: 'Plant was successfully updated.' }
        format.json { render :show, status: :ok, location: @plant }
      else
        format.html { render :edit }
        format.json { render json: @plant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /plants/1
  # DELETE /plants/1.json
  def destroy
    @plant.destroy
    respond_to do |format|
      format.html { redirect_to plants_url, notice: 'Plant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private  
    def sort_column  
       Plant.column_names.include?(params[:sort]) ? params[:sort] : "name"    
    end  
 
    
    # Use callbacks to share common setup or constraints between actions.
    def set_plant
      @plant = Plant.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def plant_params
       params.require(:plant).permit(:name, :plant_type, :plant_group, :water_amount_id, :harvest_type_id, :comment)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def sortable(title = nil, column)  
    title ||= column.titleize  
    css_class = (column == sort_column) ? "current #{sort_direction}" : nil  
    font_icon = (column == sort_column) ? "<i class=\"fi-up-arrow small\"></i>" : nil  
    direction = (column == sort_column && sort_direction == "asc") ? "desc" : "asc"  
     link_to raw("#{font_icon} #{title}"), {:sort => column, :direction => direction}, {:class => css_class}  
  end  
end

app/helpers/base_helper.rb
module BaseHelper
end

app/helpers/daily_data_helper.rb
module DailyDataHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/moon_phases_helper.rb
module MoonPhasesHelper
end

app/helpers/plantings_helper.rb
module PlantingsHelper
end

app/helpers/plants_helper.rb
module PlantsHelper
end

app/helpers/soils_helper.rb
module SoilsHelper
end

app/views/plants/_form.html.erb
<div class="row">
   <div class="small-12 columns">
      <%= simple_form_for(@plant) do |f| %>
         <% if @plant.errors.any? %>
            <div class="div.alert-box.alert.round" id="error_explanation">
               <h2><%= pluralize(@plant.errors.count, "error") %> prohibited this plant from being saved:</h2>
               <ul>
                  <% @plant.errors.full_messages.each do |message| %>
                     <li><%= message %></li>
                  <% end %>
               </ul>
            </div>
         <% end %>
         <%= f.input :name %>
         <%= f.input :plant_type %>
         <%= f.input :plant_group %>
         <%= f.association :harvest_type, collection: HarvestType.all, prompt: false %>
         <%= f.association :water_amount, collection: WaterAmount.all, prompt: false %>
         <%= f.input :comment %>
         <%= f.button :submit %>
      <% end %>
   </div>
</div>

app/views/plants/edit.html.erb
<h1>Editing plant</h1>

<%= render 'form' %>
<div class="small-4 columns">
      <%= link_to 'All Plants', plants_path %>
   </div>
   <div class="small-4 columns">
      <%= link_to 'Show', @plant %>
   </div>
   <div class="small-4 columns">
      <%= link_to 'New Plant', new_plant_path %>
   </div>

app/views/plants/index.html.erb
<div class="row">
  <div class="small-12 columns">
     <h1>Listing plants</h1>
      <p class="text-left"><%= link_to 'New Plant', new_plant_path, { :class=>"button small round success" } %></p>

      <table>
        <thead>
          <tr>
            <th><%= sortable "Name" %></th>
            <th><%= sortable "Type", "plant_type" %></th>
            <th><%= sortable "Group",  "plant_group" %></th>
             <th><%= sortable "Harvest type",  "harvest_type_id" %></th>
             <th><%= sortable "Water amount",  "water_amount_id" %></th>
            <th>Comment</th>
            <th colspan="2"></th>
          </tr>
        </thead>

        <tbody>
          <% @plants.each do |plant| %>
            <tr>
               <td><%= plant.name %></td>
               <td><%= plant.plant_type %></td>
               <td><%= plant.plant_group %></td>
               <td><%= plant.harvest_type.name if plant.harvest_type %></td>
               <td><%= plant.water_amount.name if plant.water_amount %></td>
               <td><%= plant.comment %></td>
               <td><%= link_to raw('<i class="fi-pencil small"></i>'), edit_plant_path(plant)%> |
                  <%= link_to raw('<i class="fi-eye medium"></i>'), plant, :title => "View this plant" %> |
                  <%= link_to raw('<i class="fi-trash large"></i>'), plant_path(plant), method: :delete, data: { confirm: 'Are you sure you want to remove this plant?' } %>
            </tr>
          <% end %>
        </tbody>
      </table>

      <br>
      <p class="text-left"><%= link_to 'New Plant', new_plant_path, { :class=>"button small round success" } %></p>
      <div class="row">
         <div class="small-4 columns">
            <p class="text-left"><%= link_to 'Locations', locations_path, { :class=>"button small round disabled" } %></p>
         </div>
         <div class="small-4 columns">
            <b><p class="text-center"><%= link_to 'Active Plants', active_plants_path, { :class=>"button small round disabled" } %></p></b>
         </div>
         <div class="small-4 columns">
            <p class="text-right"><%= link_to 'Soils', soils_path, { :class=>"button small round disabled" } %></p>
         </div>
      </div>
   </div>      
</div>

app/views/plants/new.html.erb
<h1>New plant</h1>

<%= render 'form' %>

<div class="row">
   <div class="small-12 columns">
      <div class="small-4 columns">
         <%= link_to 'All Plants', plants_path %>
      </div>
      <div class="small-4 columns">
         
      </div>
      <div class="small-4 columns">
         
      </div>
   </div>
</div>

app/views/plants/show.html.erb
<div class="row">
  <div class="small-12 columns">
      <p id="notice"><%= notice %></p>

      <p>
        <strong>Name:</strong>
        <%= @plant.name %>
      </p>

      <p>
        <strong>Type:</strong>
        <%= @plant.plant_type %>
      </p>

      <p>
        <strong>Group:</strong>
        <%= @plant.plant_group %>
      </p>

      <p>
        <strong>Harvest Type:</strong>
         <%= @plant.harvest_type.name %>
      </p>

      <p>
        <strong>Water amount:</strong>
         <%= @plant.water_amount.name %>
      </p>

      <p>
        <strong>Comment:</strong>
        <%= @plant.comment %>
      </p>
   </div>
</div>
<div class="row">
   <div class="small-12 columns">
      <div class="small-4 columns">
         <%= link_to 'All Plants', plants_path %>
      </div>
      <div class="small-4 columns">
         <%= link_to 'Edit', edit_plant_path(@plant) %>
      </div>
      <div class="small-4 columns">
         <%= link_to 'New Plant', new_plant_path %>
      </div>
   </div>
</div>