config/routes.rb
Rails.application.routes.draw do
  resources :harvesting_records

  resources :plantings

  resources :active_plants
  

  resources :active_plant_records

  resources :harvest_types

  resources :daily_records

  resources :soils

  resources :moon_phases

  resources :plant_statuses

  resources :plants

   post 'locations/edit_multiple', :to => 'locations#edit_multiple', :as => 'locations_edit_multiple' 

  put 'locations/update_multiple', :to =>  'locations#update_multiple', :as => 'locations_update_multiple' 
   
  resources :locations
  
   

  resources :water_amounts

  root 'base#index'

end

app/models/active_plant.rb
class ActivePlant < ActiveRecord::Base
   belongs_to :plant, class_name: "Plant"
   belongs_to :plant_status, class_name: "PlantStatus"
   belongs_to :location, class_name: "Location"
   belongs_to :soil, class_name: "Soil"
   has_many :harvest_records
   has_one :planting
   
   
   attr_accessor :date_planted, :nutrients_added, :watered

   validates :plant_id, :location_id, :plant_status_id, :count_active, presence: true

end

app/models/active_plant_record.rb
class ActivePlantRecord < ActiveRecord::Base
   belongs_to :active_plant
   belongs_to :plant_status   
end

app/models/daily_record.rb
class DailyRecord < ActiveRecord::Base
   #enum precipitation: { "None" => 0, "Dew" => 1, "Sprinkled" => 2, "Light Shower" => 3, "Quick Rain" => 4, "Rain" => 5, "Long Rain" => 6, "Heavy Rain" => 7, "Serious Rain" => 8, "Almost Flood" => 9, "Cats and Dogs" => 10 }
   belongs_to :moon_phase
   
   validates :daily_date, :weather, presence: true
   validates :temp_high, :temp_low, :eggs_collected, :total_ducks, :moon_percent, :precipitation, numericality: true
   
   validates :daily_date, uniqueness: true
end

app/models/harvest_type.rb
class HarvestType < ActiveRecord::Base
end

app/models/harvesting_record.rb
class HarvestingRecord < ActiveRecord::Base
   belongs_to :active_plant, class_name: "ActivePlant"
   belongs_to :weight_type, class_name: "WeightType"
   
   validates :active_plant_id, :date_harvested, :count_harvested, :weight_type_id, presence: true

end

app/models/location.rb
class Location < ActiveRecord::Base
   validates :name, :soil_id, presence: true
   belongs_to :soil, class_name: "Soil"
   
end

app/models/moon_phase.rb
class MoonPhase < ActiveRecord::Base
end

app/models/plant.rb
class Plant < ActiveRecord::Base   
   belongs_to :harvest_type
   belongs_to :water_amount
   belongs_to :plant_status
   validates :name, uniqueness: true
   validates :name, :plant_type, :plant_group,  presence: true #:harvest_type_id, :water_amount_id,
   #
end

app/models/plant_status.rb
class PlantStatus < ActiveRecord::Base
end

app/models/planting.rb
class Planting < ActiveRecord::Base
   belongs_to :active_plant
   belongs_to :plant_status
   belongs_to :location
   belongs_to :soil
   
end

app/models/soil.rb
class Soil < ActiveRecord::Base
      validates :name, presence: true

end

app/models/water_amount.rb
class WaterAmount < ActiveRecord::Base
  validates :name, presence: true
end

app/models/weight_type.rb
class WeightType < ActiveRecord::Base
  validates :name, presence: true
end

app/controllers/base_controller.rb
class BaseController < ApplicationController
end

app/controllers/plantings_controller.rb
class PlantingsController < ApplicationController
  helper_method :sort_column, :sort_direction
  before_action :set_planting, only: [:show, :edit, :update, :destroy]

  # GET /plantings
  # GET /plantings.json
  def index
     if(!params[:sort].nil?)
        @plantings = Planting.joins(active_plant: :plant).order(params[:sort] + ' ' + params[:direction]).all
     else
        @plantings = Planting.all
     end
  end

  # GET /plantings/1
  # GET /plantings/1.json
  def show
  end

  # GET /plantings/new
  def new
    @planting = Planting.new
  end

  # GET /plantings/1/edit
  def edit
  end

  # POST /plantings
  # POST /plantings.json
  def create
    @planting = Planting.new(planting_params)

    respond_to do |format|
      if @planting.save
        format.html { redirect_to @planting, notice: 'Planting was successfully created.' }
        format.json { render :show, status: :created, location: @planting }
      else
        format.html { render :new }
        format.json { render json: @planting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /plantings/1
  # PATCH/PUT /plantings/1.json
  def update
    respond_to do |format|
      if @planting.update(planting_params)
        format.html { redirect_to @planting, notice: 'Planting was successfully updated.' }
        format.json { render :show, status: :ok, location: @planting }
      else
        format.html { render :edit }
        format.json { render json: @planting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /plantings/1
  # DELETE /plantings/1.json
  def destroy
    @planting.destroy
    respond_to do |format|
      format.html { redirect_to plantings_url, notice: 'Planting was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
   
   private  
    def sort_column  
       Planting.column_names.include?(params[:sort]) ? params[:sort] : "date_planted"    
    end
   
    def set_planting
      @planting = Planting.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def planting_params
      params.require(:planting).permit(:active_plant_id, :plant_status_id, :location_id, :count_planted, :date_planted)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def sortable(title = nil, column)  
    title ||= column.titleize  
    css_class = (column == sort_column) ? "current #{sort_direction}" : nil  
    font_icon = (column == sort_column) ? "<i class=\"fi-up-arrow small\"></i>" : nil  
    direction = (column == sort_column && sort_direction == "asc") ? "desc" : "asc"  
     link_to raw("#{font_icon} #{title}"), {:sort => column, :direction => direction}, {:class => css_class}  
  end  
end

app/helpers/base_helper.rb
module BaseHelper
end

app/helpers/daily_data_helper.rb
module DailyDataHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/moon_phases_helper.rb
module MoonPhasesHelper
end

app/helpers/plantings_helper.rb
module PlantingsHelper
end

app/helpers/plants_helper.rb
module PlantsHelper
end

app/helpers/soils_helper.rb
module SoilsHelper
end

app/views/plantings/_form.html.erb
<div class="row">
  <div class="small-12 columns">
     <%= simple_form_for(@planting) do |f| %>
        <% if @planting.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@planting.errors.count, "error") %> prohibited this planting from being saved:</h2>
            <ul>
            <% @planting.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
            </ul>
          </div>
     <% end %>
     <%= f.input :active_plant_id, collection: ActivePlant.all, label_method: lambda { |ap| "#{ap.plant.name} | #{ap.location.name}" }, prompt: "Choose wisely" %>
     <%= f.input :location_id, collection: Location.all, label_method: lambda { |w| "#{w.name}" } %>
     <%= f.input :plant_status_id, collection: PlantStatus.all, label_method: lambda { |w| "#{w.name}" } %>
     <%= f.input :count_planted %>
     <%= f.input :date_planted %>

     <%= f.button :submit %>

   <% end %>

app/views/plantings/_show.html.erb
     <p id="notice"><%= notice %></p>
     <p>
        <strong>Active plant:</strong>
        <%= @planting.active_plant.plant.name   %>
     </p>

     <p>
        <strong>Status:</strong>
        <%= @planting.plant_status.name %>
     </p>

     <p>
        <strong>Location:</strong>
        <%= @planting.location.name if @planting.location%>
     </p>

     <p>
        <strong>Count planted:</strong>
        <%= @planting.count_planted %>
     </p>

     <p>
        <strong>Date planted:</strong>
        <%= @planting.date_planted %>
     </p>

app/views/plantings/edit.html.erb
<h1>Editing planting</h1>

<%= render 'form' %>

<%= link_to 'Show', @planting %> |
<%= link_to 'All Plantings', plantings_path %>

app/views/plantings/index.html.erb
<div class="row">
  <div class="small-12 columns">
      <h1>Listing plantings</h1>
      <%= link_to 'New AP', new_active_plant_path, { :class=>"button small round success" } %>
      <table>
        <thead>
          <tr>
             <th><%= sortable "Active plant", "plants.name" %></th>
            <th><%= sortable "Status", "plant_status_id" %></th>
            <th><%= sortable "Location", "location_id" %></th>
            <th><%= sortable "Count", "count_planted" %></th>
            <th><%= sortable "Date", "date_planted" %></th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @plantings.each do |planting| %>
            <tr>
               <% if !planting.active_plant.nil? %>
                  <% p_name = "#{planting.active_plant.plant.name}, #{planting.active_plant.plant.plant_type}" %>
                  <td><%= link_to p_name, active_plant_path(planting.active_plant_id)%></td>
               <% else %>
                  <td>Error</td>
               <% end %>
               <td><%= planting.plant_status.name if planting.plant_status %></td>
               <td><%= planting.location.name if planting.location %></td>
               <td><%= planting.count_planted %></td>
               <td><%= planting.date_planted %></td>
               <td><%= link_to raw('<i class="fi-pencil"></i>'), edit_planting_path(planting), :title => "Edit this Planting" %> |
                  <%= link_to raw('<i class="fi-eye"></i>'), planting, :title => "View this planting" %> | 
              <%= link_to raw('<i class="fi-trash"></i>'), planting, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <br>
      <%= link_to 'New AP', new_active_plant_path, { :class=>"button small round success" } %>
      <div class="row">
         <div class="small-4 columns">
            <%= link_to 'Active Plants', active_plants_path, { :class=>"button small round disabled" }  %>
         </div>
         <div class="small-4 columns">
            <p class="text-center"><%= link_to 'Harvests', harvesting_records_path, { :class=>"button small round disabled" }  %> </p>
         </div>
         <div class="small-4 columns">
            <p class="text-right"><%= link_to 'Records', active_plant_records_path, { :class=>"button small round disabled" }  %></p>
         </div>
      </div>
   </div>
</div>
 

app/views/plantings/new.html.erb
<h1>New planting</h1>

<%= render 'form' %>

<%= link_to 'All Plantings', plantings_path %>

app/views/plantings/show.html.erb
<div class="row">
  <div class="small-12 columns">
     <%= render 'show' %>

     <%= link_to 'Edit', edit_planting_path(@planting) %> |
     <%= link_to 'All Plantings', plantings_path %>
   </div>
</div>